# Site settings
title: 张文庆的博客
SEOTitle: 张文庆的博客 | web apps, programming talk, and random thoughts
header-img: img/head-bg/home.jpg
email: 6199599@gmail.com
description: 'web apps, programming talk, and random thoughts'
keyword: ''
url: 'https://z0p.github.io/' # your host, for absolute URL
baseurl: '' # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: z0p
telegram_username: github1s

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ['less', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md']
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# giscus settings
giscus_username: z0p

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: '有意义的活着。'
sidebar-avatar: https://github.com/z0p.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: '#000000'
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true
# Friends
# friends:
#   [
#     { title: "abc", href: "http://def.com" }
#   ]
